services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: easy
      SERVER_NAME: "Pipoca and Nanah's Place"
      ALLOW_LIST: "false"   # true por padrao na imagem; sem isso ninguem entra sem allowlist manual
      LEVEL_SEED: "5480987504042101543"
      # Veja mais variaveis em: https://github.com/itzg/docker-minecraft-bedrock-server
    ports:
      - "19132:19132/udp"   # acesso direto na rede local
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true

  frpc:
    image: fatedier/frpc:v0.71.0
    container_name: frpc
    restart: unless-stopped
    environment:
      FRP_TOKEN: "${FRP_TOKEN}"
    volumes:
      - ./frp/frpc.toml:/etc/frp/frpc.toml:ro
    command: ["-c", "/etc/frp/frpc.toml"]
    depends_on:
      - bedrock
